/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Benefits.module.css";

const BenefitItem = ({ icon, title, descriptions }) => (
  <div className={styles.benefitItem}  style={{ backgroundColor: 'rgba(21, 7, 12, 1)'}}>
    <div className={styles.benefitHeader}>
      <img loading="lazy" src={icon} alt="" className={styles.benefitIcon} />
      <h3 className={styles.benefitTitle}>{title}</h3>
    </div>
    {descriptions.map((desc, index) => (
      <div key={index} className={styles.benefitDescription}>
        <h4 className={styles.descriptionTitle}>{desc.title}</h4>
        <p className={styles.descriptionText}>{desc.text}</p>
      </div>
    ))}
  </div>
);

const Benefits = () => {
  const benefitsData = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b1c60abdd7e36799d36aaa127992805318d14b32853e8d018661bbdae554b7b0?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      title: "Customization and Flexibility",
      descriptions: [
        {
          title: "Unique Design",
          text: "Unlike website builders like WordPress or Wix, we create custom websites tailored to your specific needs, giving your brand a unique identity with a distinct look and feel.",
        },
        {
          title: "Personalized Functionality",
          text: "Custom websites offer limitless possibilities, without the restrictions of standard website builders.",
        },
      ],
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ee3962aa43f67ec5c655e4a3ae876856d4809b31598a37eb8fc83970631cf373?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      title: "Performance and Optimization",
      descriptions: [
        {
          title: "Speed and Efficiency",
          text: "Our websites are fast and efficient, developed with only the necessary code.",
        },
        {
          title: "SEO Optimization",
          text: "Fully optimized for search engines to maximize your visibility.",
        },
      ],
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/440816c8c3af586c52ed7d6e0278bed02f275bfd4ed63cd8f9012fa593219ae2?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      title: "Scalability",
      descriptions: [
        {
          title: "Growth and Flexibility",
          text: "As your business grows, your website can grow with it, without limitations.",
        },
        {
          title: "Integration with Third-Party Tools",
          text: "Seamless integration with any external tool for robust business solutions.",
        },
      ],
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/2c5d48c3c05bcbc4af18c2a302e9ba6024ae90fb33d233c7831ec2c5df62fd01?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      title: "Security",
      descriptions: [
        {
          title: "Enhanced Security",
          text: "Developed with stronger security measures to prevent hacks.",
        },
        {
          title: "Regular Updates",
          text: "Ability to update regularly without dependency on third parties.",
        },
      ],
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e0bbd4680dcad845b351652fe3d07ea1deb527498a993b01df90843e7ea66605?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      title: "Ownership and Control",
      descriptions: [
        {
          title: "Full Ownership",
          text: "You have complete ownership of the code and design.",
        },
        {
          title: "No Vendor Lock-In",
          text: "Freedom to choose and move without restrictions",
        },
      ],
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/5a6e8b91cdfc353df96206a6cdf9c11db1d13c742c5c582003a92d97d693ffe2?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      title: "Professionalism and Credibility",
      descriptions: [
        {
          title: "Personalized Experience",
          text: "A custom website demonstrates your commitment to quality and professionalism.",
        },
        {
          title: "Competitive Advantage",
          text: "A distinctive website helps you stand out from the competition.",
        },
      ],
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/f44ab624d48f269e04b0f5fbcea59604fec17b5c3bc4a9dc5d35667f1b523f81?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      title: "Long-Term Cost Efficiency",
      descriptions: [
        {
          title: "Avoid Hidden Costs",
          text: "Custom websites are more cost-effective in the long run.",
        },
        {
          title: "Maintenance and Upgrades",
          text: "Easy maintenance and upgrades tailored to your business needs.",
        },
      ],
    },
  ];

  return (
    <section  style={{ backgroundColor: 'rgba(21, 7, 12, 1)'}} >
        <h2 className={styles.title}>Benefits of a Custom Website</h2>
        <div className={styles.benefits}>
      {benefitsData.map((benefit, index) => (
        <BenefitItem key={index} {...benefit} />
      ))}
      </div>
    </section>
  );
};

export default Benefits;
