/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ContactForm.module.css";

const ContactForm = () => {
  return (
    <section className="grid grid-cols-1 md:grid-cols-2 bg-[#2e0a16] rounded-2xl p-6 mx-4">
      <div className={styles.formWrapper}>
        <h2 className={styles.formHeading}>Contact Us</h2>
        <form className={styles.form}>
          <div className="flex gap-5 flex-col md:flex-row">
            <input
              type="text"
              className="w-full p-4 rounded-md  bg-[#391622] border border-[#60454e]"
              placeholder="First Name"
              aria-label="First Name"
            />
            <input
              type="text"
              className="w-full p-4 rounded-md  bg-[#391622] border border-[#60454e]"
              placeholder="Last Name"
              aria-label="Last Name"
            />
          </div>
          <input
            type="email"
            className={styles.input}
            placeholder="Email"
            aria-label="Email"
          />
          <input
            type="tel"
            className={styles.input}
            placeholder="Phone Number"
            aria-label="Phone Number"
          />
          <textarea
            className={styles.textarea}
            placeholder="Message"
            aria-label="Message"
          ></textarea>
          <button type="submit" className={styles.submit}>
            <span>Send it to the moon</span>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/b2dd7e79d8e192de49576b43d8a31edae63d0e54eb5d9e1a818357204f1e2573?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a"
              alt=""
              className={styles.submitIcon}
            />
          </button>
        </form>
      </div>
      <div className={styles.imageBox}>
        <div className={styles.image} aria-hidden="true"></div>
      </div>
    </section>
  );
};

export default ContactForm;
