/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import styles from "./FAQ.module.css";

const FAQItem = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className={styles.faqItem}>
      <button
        className={styles.faqToggle}
        onClick={() => setIsOpen(!isOpen)}
        aria-expanded={isOpen}
      >
        <span className={styles.faqQuestion}>{question}</span>
        <img
          loading="lazy"
          src={
            isOpen
              ? "https://cdn.builder.io/api/v1/image/assets/TEMP/78c81f0aca6e0e76849b4744c607f4440a2d8a95b853d1e584379a4c47db77dd?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a"
              : "https://cdn.builder.io/api/v1/image/assets/TEMP/b09aac9dc0e831e4e4575dc05e947c61f08806ff87aa47b3fdfa0a637c5a7e7c?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a"
          }
          alt={isOpen ? "Collapse" : "Expand"}
          className={styles.faqIcon}
        />
      </button>
      {isOpen && <p className={styles.faqAnswer}>{answer}</p>}
    </div>
  );
};

const FAQ = () => {
  const faqData = [
    {
      question: "How long does it take to build a website?",
      answer:
        "Depending on the complexity, a standard website can be delivered within 2-4 weeks.",
    },
    {
      question: "Can I modify the website later?",
      answer:
        "Yes, you can modify the website later. We provide you with access to the content management system, allowing you to make changes to your content independently.",
    },
    {
      question: "Do you also offer hosting services?",
      answer:
        "Yes, we offer hosting services as part of our website development package. This ensures your website is properly set up and maintained on reliable servers.",
    },
  ];

  return (
    <section className={styles.faqSection}  style={{ backgroundColor: 'rgba(21, 7, 12, 1)'}}>
      <h2 className={styles.faqTitle}>Frequently asked questions</h2>
      <div className={styles.faqList}>
        {faqData.map((item, index) => (
          <FAQItem key={index} question={item.question} answer={item.answer} />
        ))}
      </div>
    </section>
  );
};

export default FAQ;
