/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

const Footer = () => {
  return (
    <footer
      className="border-t p-4"
      style={{ backgroundColor: "rgba(21, 7, 12, 1)" }}
    >
      <div className="flex flex-col md:flex-row justify-between items-center  ">
        <div className={styles.logo}>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0d2719a874bfc55c896b536adff07c11678b83bf6f5b56a404387eb5dc665409?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a"
            alt="Company Logo"
            className={styles.logoImage}
          />
        </div>
        <nav className={styles.footerNav}>
          <a href="/terms" className={styles.footerLink}>
            Terms
          </a>
          <a href="/privacy" className={styles.footerLink}>
            Privacy
          </a>
          <a href="/support" className={styles.footerLink}>
            Support
          </a>
        </nav>
        <div className={styles.socialIcons}>
          <a href="#" aria-label="Facebook">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/dcb4dc3e4cd889da146704620af889ed1557b8380a910f2f29ec29efae3428e9?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a"
              alt=""
              className={styles.socialIcon}
            />
          </a>
          <a href="#" aria-label="Twitter">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/93412e7849d7687cd9525fa2bfc232266cf08fb8eb876f431c074d8ecc2e8395?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a"
              alt=""
              className={styles.socialIcon}
            />
          </a>
          <a href="#" aria-label="Instagram">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d87587a0998ecaca7add12dcddd4bb63f660661db0359d3decbc42d93ef29ca0?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a"
              alt=""
              className={styles.socialIcon}
            />
          </a>
          <a href="#" aria-label="LinkedIn">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e47f88fe9b5142872b059954e7cc9f7ebd4a8da7bc37e7881d9e85425a8af3e?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a"
              alt=""
              className={styles.socialIcon}
            />
          </a>
          <a href="#" aria-label="YouTube">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/1b68f8e32b0fb770c38258f7333a2098380a0f4dccc8314c0a57c82d7e54ae11?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a"
              alt=""
              className={styles.socialIcon}
            />
          </a>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
