/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Hero.module.css";
import Line from "./verticalline/Line";



const Hero = () => {
  return (
    <section className={styles.hero}>
      <Line/>
      <div className={styles.content}>
        <div className={styles.mainHeadline}>

          <span className={styles.regularText}>Your new website for </span>
          <span className={styles.highlightedText}>$300</span>
        </div>
        <p className={styles.subheadline}>
          Join the leaders in the industry with a custom website, built <br/>with the
          technology of the future.
        </p>
        <p className={styles.locationText}>
          Websites for starting & established <br/>businesses in{" "}
          <span className={styles.locationHighlight}>Haarlem</span>
        </p>
      </div>
    </section>
  );
};

export default Hero;























// /**
//  * This code was generated by Builder.io.
//  */
// import React from "react";
// import { Box, Typography, Container } from "@mui/material";
// import Line from "./verticalline/Line"; // Assuming Line is already a separate component

// const Hero = () => {
//   return (
//     <Box
//       component="section"
//       sx={{
//         position: 'relative',
//         backgroundColor: 'rgba(21, 7, 12, 1)',
//         padding: '20px',
//         display: 'flex',
//         alignItems: 'center',
//         justifyContent: 'center',
//         height: '100vh',
//       }}
//     >
//       <Line />
//       <Container maxWidth="md" sx={{ textAlign: 'center' }}>
//         <Typography
//           variant="h1"
//           component="div"
//           sx={{
//             fontWeight: 'bold',
//             color: 'white',
//             fontSize: { xs: '2.5rem', sm: '3.5rem', md: '4rem' },
//           }}
//         >
//           Your new website for{' '}
//           <Typography
//             component="span"
//             sx={{
//               color: '#ff007f',
//               fontSize: { xs: '2.5rem', sm: '3.5rem', md: '4rem' },
//             }}
//           >
//             $300
//           </Typography>
//         </Typography>

//         <Typography
//           variant="body1"
//           sx={{
//             color: 'white',
//             fontSize: { xs: '1rem', sm: '1.2rem', md: '1.5rem' },
//             marginTop: '20px',
//           }}
//         >
//           Join the leaders in the industry with a custom website, built with the
//           technology of the future.
//         </Typography>

//         <Typography
//           variant="body2"
//           sx={{
//             color: 'rgba(255, 255, 255, 0.8)',
//             fontSize: { xs: '0.9rem', sm: '1rem', md: '1.2rem' },
//             marginTop: '10px',
//           }}
//         >
//           Websites for starting & established businesses in{' '}
//           <Typography
//             component="span"
//             sx={{
//               color: '#ff007f',
//             }}
//           >
//             Haarlem
//           </Typography>
//         </Typography>
//       </Container>
//     </Box>
//   );
// };

// export default Hero;
