/**
 * This code was generated by Builder.io.
 */
import React from "react";

import Line from "./verticalline/Line";

const Hero = () => {
  return (
    <section
      className="text-white"
      style={{ backgroundColor: "rgba(21, 7, 12, 1)" }}
    >
      <div className="flex">
        <div className="h-[500px]">
          <Line />
        </div>
        <div className="flex flex-col gap-5">
          <div className="pt-10">
            <h1 className="p-0 text-start text-3xl md:text-6xl font-bold w-full">
              Your new website for <span className="text-[#dc1e5e]">$300</span>
            </h1>
          </div>
          <p className="text-slate-400 w-2/3  md:text-lg">
            Join the leaders in the industry with a custom website, built <br />
            with the technology of the future.
          </p>
          <h2 className="text-2xl md:text-3xl font-bold">
            Websites for starting & established <br />
            businesses in <span className="text-[#dc1e5e]">Haarlem</span>
          </h2>
        </div>
      </div>
    </section>
  );
};

export default Hero;

// /**
//  * This code was generated by Builder.io.
//  */
// import React from "react";
// import { Box, Typography, Container } from "@mui/material";
// import Line from "./verticalline/Line"; // Assuming Line is already a separate component

// const Hero = () => {
//   return (
//     <Box
//       component="section"
//       sx={{
//         position: 'relative',
//         backgroundColor: 'rgba(21, 7, 12, 1)',
//         padding: '20px',
//         display: 'flex',
//         alignItems: 'center',
//         justifyContent: 'center',
//         height: '100vh',
//       }}
//     >
//       <Line />
//       <Container maxWidth="md" sx={{ textAlign: 'center' }}>
//         <Typography
//           variant="h1"
//           component="div"
//           sx={{
//             fontWeight: 'bold',
//             color: 'white',
//             fontSize: { xs: '2.5rem', sm: '3.5rem', md: '4rem' },
//           }}
//         >
//           Your new website for{' '}
//           <Typography
//             component="span"
//             sx={{
//               color: '#ff007f',
//               fontSize: { xs: '2.5rem', sm: '3.5rem', md: '4rem' },
//             }}
//           >
//             $300
//           </Typography>
//         </Typography>

//         <Typography
//           variant="body1"
//           sx={{
//             color: 'white',
//             fontSize: { xs: '1rem', sm: '1.2rem', md: '1.5rem' },
//             marginTop: '20px',
//           }}
//         >
//           Join the leaders in the industry with a custom website, built with the
//           technology of the future.
//         </Typography>

//         <Typography
//           variant="body2"
//           sx={{
//             color: 'rgba(255, 255, 255, 0.8)',
//             fontSize: { xs: '0.9rem', sm: '1rem', md: '1.2rem' },
//             marginTop: '10px',
//           }}
//         >
//           Websites for starting & established businesses in{' '}
//           <Typography
//             component="span"
//             sx={{
//               color: '#ff007f',
//             }}
//           >
//             Haarlem
//           </Typography>
//         </Typography>
//       </Container>
//     </Box>
//   );
// };

// export default Hero;
