/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Services.module.css";
import Line from "./verticalline/Line";

const ServiceCard = ({ icon, price, title, description, features }) => (
  <div
    className="border border-slate-500 rounded-3xl p-10 gap-5 flex flex-col items-center"
    style={{ backgroundColor: "rgba(21, 7, 12, 1)" }}
  >
    <img
      loading="lazy"
      src={icon}
      alt={`${title} icon`}
      className=" w-20 h-20"
    />

    <div className="flex flex-col items-center">
      <h1 className="text-2xl sm:text-4xl md:text-6xl font-bold text-center p-0">
        {price}
      </h1>
      <h3 className="text-lg sm:text-xl md:text-2xl ">{title}</h3>
      <p className="text-slate-500">{description}</p>
    </div>
    <button className="border border-[#dc1e5e] w-full rounded-3xl  p-3">
      View Our Services
    </button>
    <ul className="flex flex-col gap-4 md:gap-6">
      {features.map((feature, index) => (
        <li key={index} className="flex gap-3 uppercase">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ef1c968292488f7f43c81b3b88a4da951c63c4a34cd1ce16916abdefa51d1eb0?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a"
            alt=""
            className={styles.featureIcon}
          />
          <span className="sm:text-sm md:text-base">{feature}</span>
        </li>
      ))}
    </ul>
  </div>
);

const Services = () => {
  const services = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e8cfc1cbba518a2f4137a4e0387b9788bfa40e579de9c21be33ab0f5f102c1b3?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      price: "$35",
      title: "Logo Design",
      description: "Stylish logo design",
      features: [
        "Original emblem",
        "High-quality logo",
        "Without background",
        "Multiple file formats (PNG, JPG, JPEG)",
      ],
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e740522ec9ef20fed5120f393a2eaf244e4b49864a3534793f28431dc0589fe1?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      price: "$300",
      title: "Website Development",
      description: "Professional, custom-built website",
      features: [
        "Own website",
        "Management panel – to edit content independently",
        "Website files",
        "Free hosting for the website",
        "Free backup",
      ],
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4b0e71b896dcc6872467d48b33e7e0edb60060d7452528e4429a374012298d12?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      price: "$50",
      title: "Logo + Animation",
      description: "Personalized logo with animation",
      features: [
        "Original emblem",
        "Everything from the Logo package",
        "High-quality animated logo (1440p / 1080p)",
      ],
    },
  ];

  return (
    <section
      className="my-20 text-white  overflow-x-hidden"
      style={{ backgroundColor: "rgba(21, 7, 12, 1)" }}
    >
      <div className="flex gap-7">
        <Line />
        <div>
          <h1 className="p-0 text-start text-2xl md:text-6xl font-bold w-1/2  my-10">
            Our Services
          </h1>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 me-7">
            {services.map((service, index) => (
              <ServiceCard key={index} {...service} />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Services;
