/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Services.module.css";
import Line from "./verticalline/Line";

const ServiceCard = ({ icon, price, title, description, features }) => (
  <div className={styles.serviceCard} style={{ backgroundColor: 'rgba(21, 7, 12, 1)'}}>
    <img
      loading="lazy"
      src={icon}
      alt={`${title} icon`}
      className={styles.serviceIcon}
    />
    <div className={styles.serviceInfo}>
      <div className={styles.servicePrice}>{price}</div>
      <h3 className={styles.serviceTitle}>{title}</h3>
      <p className={styles.serviceDescription}>{description}</p>
    </div>
    <button className={styles.viewServicesButton}>View Our Services</button>
    <ul className={styles.featureList}>
      {features.map((feature, index) => (
        <li key={index} className={styles.featureItem}>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ef1c968292488f7f43c81b3b88a4da951c63c4a34cd1ce16916abdefa51d1eb0?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a"
            alt=""
            className={styles.featureIcon}
          />
          <span>{feature}</span>
        </li>
      ))}
    </ul>
  </div>
);

const Services = () => {
  const services = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e8cfc1cbba518a2f4137a4e0387b9788bfa40e579de9c21be33ab0f5f102c1b3?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      price: "$35",
      title: "Logo Design",
      description: "Stylish logo design",
      features: [
        "Original emblem",
        "High-quality logo",
        "Without background",
        "Multiple file formats (PNG, JPG, JPEG)",
      ],
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e740522ec9ef20fed5120f393a2eaf244e4b49864a3534793f28431dc0589fe1?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      price: "$300",
      title: "Website Development",
      description: "Professional, custom-built website",
      features: [
        "Own website",
        "Management panel – to edit content independently",
        "Website files",
        "Free hosting for the website",
        "Free backup",
      ],
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4b0e71b896dcc6872467d48b33e7e0edb60060d7452528e4429a374012298d12?placeholderIfAbsent=true&apiKey=9017a87510fe476c98d2c8c4751e147a",
      price: "$50",
      title: "Logo + Animation",
      description: "Personalized logo with animation",
      features: [
        "Original emblem",
        "Everything from the Logo package",
        "High-quality animated logo (1440p / 1080p)",
      ],
    },
  ];

  return (
    <section className={styles.services}  style={{ backgroundColor: 'rgba(21, 7, 12, 1)'}}>
      <div style={{position: 'absolute', marginLeft:'80px',height: '100%',marginTop:'30px'}}>
       <Line/>
       </div>
      <h2 className={styles.sectionTitle}>Our Services</h2>
      <div className={styles.serviceGrid}>
        {services.map((service, index) => (
          <ServiceCard key={index} {...service} />
        ))}
      </div>
    </section>
  );
};

export default Services;
